#ifndef _GUISLICE_WRAPPER_ENUM_H_
#define _GUISLICE_WRAPPER_ENUM_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus


enum {
  E_FONT_MONO14,
  E_FONT_MONO2,
  E_FONT_MONO18,
  E_FONT_MONO24,
  E_FONT_MONO28,
  MAX_FONT
};

#define MAX_FONTS MAX_FONT

enum {
  E_ELEM_IBTN1,
  E_ELEM_BTN_UP_ARROW,
  E_ELEM_BTN_RIGHT_ARROW,
  E_ELEM_BTN_DOWN_ARROW,
  E_ELEM_BTN_LEFT_ARROW,
  E_ELEM_BTN_SELECT,
  E_ELEM_BTN_BACK_ARROW,
  E_ELEM_BTN_HOME,
  E_ELEM_BTN_PAGE_DOWN,
  E_ELEM_BTN_PAGE_UP,

  E_ELEM_BTN_VOLUME_DOWN,
  E_ELEM_BTN_VOLUME_UP,
  E_ELEM_BTN_VOLUME_MUTE,


  E_SLIDER_PLAYER,
  E_BTN_PLAYER_STOP,
  E_BTN_PLAYER_PLAY,
  E_BTN_PLAYER_PAUSE,

  E_BTN_PLAYER_VOLUME_ONLY,
  E_BTN_PLAYER_MOVE_BACK_SINGLE,
  E_BTN_PLAYER_MOVE_BACK,
  E_BTN_PLAYER_MOVE_FORWARD_SINGLE,
  E_BTN_PLAYER_MOVE_FORWARD,
  E_BTN_PLAYER_PLAY_SLOW,
  E_BTN_PLAYER_VOLUME,
  E_BTN_PLAYER_RATE_50,
  E_BTN_PLAYER_RATE_70,
  E_BTN_PLAYER_RATE_85,
  E_BTN_PLAYER_RATE_100,

  E_ELEM_BTN_VIDEO_RATE,
  E_ELEM_BTN_SCORECARD_1,
  E_ELEM_BTN_SCORECARD_2,
  E_SLIDER_SCORECARD,
  E_SLIDER_BTN_UP,
  E_SLIDER_BTN_DOWN,
  
  E_ELEM_VIDEO_FOLDER,
  E_ELEM_VIDEO_FILE,
  
  E_ELEM_VIDEO_POSITION,
  E_ELEM_VIDEO_RATE,
  E_ELEM_VIDEO_DURATION,

  E_ELEM_PLAYER_MSG_BOX,
  
  E_ELEM_SC_JUDGE_INIT,
  E_ELEM_SC_TEAM,
  E_ELEM_SC_ROUND,
  E_ELEM_SC_POINT_COUNT,
  E_ELEM_SC_SUBMIT,
  E_ELEM_SC_CLEAR,

  // Keyboard Elements
  E_ELEM_KEYBOARD_BOX,
  E_ELEM_KEYBOARD_INPUT,

  // WIFI Elements
  /// E_ELEM_WIFI_BOX,
  /// E_ELEM_WIFI_CLOSE,
  E_ELEM_WIFI_DISABLE,
  E_ELEM_WIFI_ENABLE,
  /// E_ELEM_WIFI_LIST_NETWORKS,
  /// E_ELEM_WIFI_SCAN_NETWORKS,
  E_ELEM_WIFI_REASSOCIATE,
  E_ELEM_WIFI_STATUS_IP,
  E_ELEM_WIFI_STATUS_STATE,
  E_ELEM_WIFI_STATUS_FREQ,
  E_ELEM_WIFI_STATUS_SSID,
  E_ELEM_WIFI_STATUS_MODE,

  E_ELEM_SLIDESHOW_FULLSCREEN
};

#ifdef __cplusplus
}
#endif // __cplusplus
#endif // _GUISLICE_WRAPPER_ENUM_H_
