#!/usr/bin/env bash

PART=$1
FS_TYPE=`lsblk -o name,fstype | grep ${PART} | awk '{print $2}'`

if [ ${FS_TYPE} = "exfat" ]
then
  /bin/mkdir -p /media/pi/${PART}
  /bin/mount -t exfat /dev/${PART} /media/pi/${PART}
else
  /usr/bin/pmount --umask 000 --noatime -w --sync /dev/${PART} /media/pi/${PART}
fi
